# Generated by Django 5.0.6 on 2025-11-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0004_rename_ai_asyncait_task_id_idx_ai_asyncait_task_id_93b1bb_idx_and_more'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung bài đăng được AI tạo')),
                ('hashtags', models.JSONField(default=list, help_text='Danh sách hashtags')),
                ('full_content', models.TextField(help_text='Content + hashtags đầy đủ')),
                ('agent_reasoning', models.TextField(blank=True, help_text='Lý do và suy nghĩ của agent')),
                ('generation_strategy', models.JSONField(default=dict, help_text='Strategy agent đã dùng')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_posts', to='media.media')),
                ('scheduled_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_generated_posts', to='ai.scheduledcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Post',
                'verbose_name_plural': 'Agent Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=10)),
                ('message', models.TextField(help_text='Nội dung tin nhắn')),
                ('function_calls', models.JSONField(default=list, help_text='Danh sách functions agent đã gọi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agent.agentpost')),
            ],
            options={
                'verbose_name': 'Agent Conversation',
                'verbose_name_plural': 'Agent Conversations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('generate_post', 'Generate Post'), ('analyze_schedule', 'Analyze Schedule'), ('check_system', 'Check System'), ('custom', 'Custom Task')], max_length=30)),
                ('description', models.TextField(help_text='Mô tả task')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='0-100')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.agentpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Task',
                'verbose_name_plural': 'Agent Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentpost',
            index=models.Index(fields=['user', 'status'], name='agent_agent_user_id_39ce5a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentpost',
            index=models.Index(fields=['-created_at'], name='agent_agent_created_adfe93_idx'),
        ),
    ]
