# Generated by Django 5.0.6 on 2025-12-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('variation', models.PositiveIntegerField(default=1, help_text='Variation number từ AI')),
                ('agent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agent.agentpost')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_post_images', to='media.media')),
            ],
            options={
                'verbose_name': 'Agent Post Image',
                'verbose_name_plural': 'Agent Post Images',
                'ordering': ['order'],
            },
        ),
    ]
