# Generated by Django 5.0.6 on 2025-12-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentpostimage'),
        ('media', '0001_initial'),
        ('platforms', '0004_alter_platformwebhook_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpost',
            name='target_account',
            field=models.ForeignKey(blank=True, help_text='Page sẽ đăng bài này lên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_posts_target', to='platforms.socialaccount'),
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_position', models.CharField(choices=[('top_left', 'Góc trên trái'), ('top_right', 'Góc trên phải'), ('bottom_left', 'Góc dưới trái'), ('bottom_right', 'Góc dưới phải'), ('center', 'Giữa')], default='bottom_right', help_text='Vị trí logo trên ảnh', max_length=20)),
                ('logo_size', models.IntegerField(default=15, help_text='Kích thước logo (% so với ảnh)')),
                ('auto_add_logo', models.BooleanField(default=False, help_text='Tự động thêm logo vào ảnh')),
                ('hotline', models.CharField(blank=True, help_text='Số điện thoại hotline', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Website URL')),
                ('auto_add_hotline', models.BooleanField(default=False, help_text='Tự động thêm hotline vào content')),
                ('slogan', models.CharField(blank=True, help_text='Slogan/tagline', max_length=200)),
                ('brand_colors', models.JSONField(default=list, help_text='Danh sách màu thương hiệu (hex codes)')),
                ('default_tone', models.CharField(choices=[('professional', 'Chuyên nghiệp'), ('casual', 'Thân thiện'), ('friendly', 'Gần gũi'), ('funny', 'Hài hước'), ('formal', 'Trang trọng')], default='casual', help_text='Giọng văn mặc định', max_length=20)),
                ('default_word_count', models.IntegerField(default=100, help_text='Số từ mặc định cho bài đăng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ForeignKey(blank=True, help_text='Logo mặc định cho ảnh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_settings_logo', to='media.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Settings',
                'verbose_name_plural': 'Agent Settings',
            },
        ),
    ]
