# Generated by Django 5.0.6 on 2025-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentpost_target_account_agentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpost',
            name='feed_post_url',
            field=models.URLField(blank=True, help_text='URL bài viết trên Facebook Feed'),
        ),
        migrations.AddField(
            model_name='agentpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Đã được đăng lên Facebook chưa'),
        ),
        migrations.AddField(
            model_name='agentpost',
            name='publish_error',
            field=models.TextField(blank=True, help_text='Lỗi khi đăng bài (nếu có)'),
        ),
        migrations.AddField(
            model_name='agentpost',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian đăng bài', null=True),
        ),
        migrations.AddField(
            model_name='agentpost',
            name='story_published',
            field=models.BooleanField(default=False, help_text='Đã đăng lên Story chưa'),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='default_word_count',
            field=models.IntegerField(default=150, help_text='Số từ mặc định cho bài đăng (không tính hashtags)'),
        ),
    ]
