# Generated by Django 5.0.6 on 2025-12-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_add_publishing_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpost',
            name='feed_post_url',
            field=models.URLField(blank=True, default='', help_text='URL bài viết trên Facebook Feed'),
        ),
    ]
