# Generated by Django 5.0.6 on 2025-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_socialaccount_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
