# Generated by Django 5.0.6 on 2025-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_alter_socialaccount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformwebhook',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook')], default='facebook', max_length=20),
        ),
    ]
