# Generated by Django 5.0.6 on 2025-11-26 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=255)),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('content_type', models.CharField(choices=[('pain_point', 'Pain Point'), ('educational', 'Educational'), ('social_proof', 'Social Proof'), ('engagement', 'Engagement'), ('conversion', 'Conversion'), ('lifestyle', 'Lifestyle'), ('promo', 'Promotion')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('goal', models.CharField(choices=[('awareness', 'Awareness'), ('engagement', 'Engagement'), ('conversion', 'Conversion'), ('retention', 'Retention')], max_length=50)),
                ('hook', models.TextField(help_text='Opening hook (2 lines)')),
                ('body', models.TextField(help_text='Main content body')),
                ('engagement', models.TextField(help_text='Engagement question')),
                ('cta', models.TextField(help_text='Call to action')),
                ('hashtags', models.JSONField(default=list, help_text='List of hashtags')),
                ('media_type', models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='text', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Content',
                'verbose_name_plural': 'Scheduled Contents',
                'ordering': ['schedule_date', 'schedule_time'],
            },
        ),
    ]
