# Generated by Django 5.0.6 on 2025-11-26 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=255)),
                ('goals', models.TextField(help_text='Marketing goals for this schedule')),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=20)),
                ('posts_per_day', models.IntegerField(default=2)),
                ('total_posts', models.IntegerField()),
                ('strategy_overview', models.TextField(blank=True)),
                ('hashtag_suggestions', models.JSONField(default=list)),
                ('engagement_tips', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posting Schedule',
                'verbose_name_plural': 'Posting Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledcontent',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ai.postingschedule'),
        ),
    ]
