# Generated by Django 5.0.6 on 2025-11-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_postingschedule_scheduledcontent_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncAITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('task_type', models.CharField(choices=[('content', 'Content Generation'), ('image', 'Image Generation'), ('schedule', 'Schedule Generation')], max_length=20)),
                ('input_params', models.JSONField(help_text='Task input parameters')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('result', models.JSONField(blank=True, help_text='Task result data', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total execution time in seconds', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Async AI Task',
                'verbose_name_plural': 'Async AI Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asyncaitask',
            index=models.Index(fields=['task_id'], name='ai_asyncait_task_id_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncaitask',
            index=models.Index(fields=['user', 'status'], name='ai_asyncait_user_id_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncaitask',
            index=models.Index(fields=['created_at'], name='ai_asyncait_created_at_idx'),
        ),
    ]
