# Generated by Django 5.0.6 on 2025-11-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_asyncaitask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asyncaitask',
            new_name='ai_asyncait_task_id_93b1bb_idx',
            old_name='ai_asyncait_task_id_idx',
        ),
        migrations.RenameIndex(
            model_name='asyncaitask',
            new_name='ai_asyncait_user_id_4e8a50_idx',
            old_name='ai_asyncait_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='asyncaitask',
            new_name='ai_asyncait_created_070bfe_idx',
            old_name='ai_asyncait_created_at_idx',
        ),
    ]
