# Generated by Django 5.0.6 on 2025-11-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
        ('pages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('original_content', models.TextField(blank=True, help_text='Original content before AI rewrite')),
                ('post_type', models.CharField(choices=[('text', 'Text Only'), ('photo', 'Photo'), ('video', 'Video'), ('carousel', 'Carousel'), ('link', 'Link')], default='text', max_length=20)),
                ('media_urls', models.JSONField(blank=True, default=list, help_text='List of media URLs')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('facebook_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='custom_auth.user')),
                ('facebook_pages', models.ManyToManyField(blank=True, related_name='posts', to='pages.facebookpage')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ai_provider', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='posts.post')),
            ],
            options={
                'db_table': 'post_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'created_at'], name='posts_status_def373_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_by', 'status'], name='posts_created_14df1e_idx'),
        ),
    ]
